# coupon-consumer 컨테이너 이미지
FROM --platform=$BUILDPLATFORM gradle:8-jdk17 AS builder
WORKDIR /home/gradle
COPY .. /home/gradle
RUN ./gradlew build -x test

FROM eclipse-temurin:17-jre
WORKDIR /app
RUN apt-get update && apt-get install -y mysql-client redis-tools
COPY --from=builder /home/gradle/coupon-consumer/build/libs/coupon-consumer.jar /app/coupon-consumer.jar
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=docker", "/app/coupon-consumer.jar"]
EXPOSE 8082
