spring:
  application:
    name: coupon-consumer
server:
  port: 8082

management:
  metrics:
    tags:
      application:
        ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus
