server:
  port: 8082
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  application:
    name: coupon-api
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://coupon-mysql:3306/coupon
    username: abcd
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: coupon-redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus
